### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by zhanxw** [Santy-8128/Minimac3#1]
Hi Santy,

FYI:
On Ubuntu 16.04, I got this problem when compile Minimac3:

PedigreeLoader.cpp: In member function ‘int Pedigree::TranslateSexCode(const char_, bool&)’:
PedigreeLoader.cpp:641:54: error: comparison of constant ‘2’ with boolean expression is always true [-Werror=bool-compare]
             if (result != 0 && result != 1 && result != 2)
                                                      ^
cc1plus: all warnings being treated as errors
../Makefiles/Makefile.common:81: recipe for target 'obj/PedigreeLoader.o' failed
make[3]: *_\* [obj/PedigreeLoader.o] Error 1
Makefiles/Makefile.base:15: recipe for target 'general' failed
make[2]: **\* [general] Error 2
../Library/libStatGenForMinimac3/Makefiles/Makefile.ext:50: recipe for target '../Library/libStatGenForMinimac3/libStatGen.a' failed
make[1]: **\* [../Library/libStatGenForMinimac3/libStatGen.a] Error 2
make[1]: Leaving directory '/home/zhanxw/Downloads/Minimac3/src'
Library/libStatGenForMinimac3/Makefiles/Makefile.base:15: recipe for target 'src' failed
make: **\* [src] Error 2
zhanxw@zhanxw-VirtualBox:~/Downloads/Minimac3$

**Comment by Santy-8128** [comment]
The issue was with some files in the library which had not been updated. Usually these go as warnings, but some compilers convert warnings to errors, as here.

> cc1plus: all warnings being treated as errors

I will make a new release with the library files updated. Users who run into this issue can re-download the new version. For users who did not face this issues, there is NO reason to re-download the source files.

**Comment by Santy-8128** [comment]
Hi zhanxw, 

The commit "Update LibStatGen Library" has updated the library files. Please re-download and let me know if you still have trouble.
